# Generated by Django 6.0.1 on 2026-01-14 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('os_type', models.CharField(choices=[('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('MACOS', 'macOS'), ('BOSS', 'BOSS')], max_length=20)),
                ('os_version', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('agent_version', models.CharField(max_length=20)),
                ('certificate_fingerprint', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
