# Generated by Django 6.0.1 on 2026-01-14 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cert_type', models.CharField(choices=[('DEVICE', 'Device'), ('IKE', 'IKE')], max_length=20)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('fingerprint', models.CharField(max_length=128)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='devices.device')),
            ],
        ),
    ]
