# Generated by Django 6.0 on 2026-01-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='devices.device'),
        ),
    ]
