# Generated by Django 6.0 on 2026-01-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPSecPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('ESP_TUNNEL', 'ESP Tunnel'), ('ESP_TRANSPORT', 'ESP Transport'), ('AH_TUNNEL', 'AH Tunnel'), ('AH_TRANSPORT', 'AH Transport'), ('ESP_AH', 'ESP + AH')], max_length=20)),
                ('encryption_algo', models.CharField(max_length=50)),
                ('integrity_algo', models.CharField(max_length=50)),
                ('dh_group', models.CharField(max_length=50)),
                ('ike_version', models.CharField(default='IKEv2', max_length=10)),
                ('full_tunnel', models.BooleanField(default=True)),
                ('include_subnets', models.JSONField(default=list)),
                ('exclude_subnets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
