# Generated by Django 6.0.1 on 2026-01-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tunnels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSecPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('policy_type', models.CharField(choices=[('SITE', 'Site to Site'), ('REMOTE_ACCESS', 'Remote Access')], default='REMOTE_ACCESS', max_length=20)),
                ('mode', models.CharField(choices=[('ESP_TUNNEL', 'ESP Tunnel'), ('ESP_TRANSPORT', 'ESP Transport')], default='ESP_TUNNEL', max_length=20)),
                ('encryption_algo', models.CharField(default='aes256', max_length=50)),
                ('integrity_algo', models.CharField(default='sha256', max_length=50)),
                ('dh_group', models.CharField(default='modp2048', max_length=50)),
                ('ike_version', models.CharField(default='IKEv2', max_length=10)),
                ('full_tunnel', models.BooleanField(default=False)),
                ('include_subnets', models.JSONField(default=list)),
                ('exclude_subnets', models.JSONField(default=list)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tunnels', models.ManyToManyField(blank=True, related_name='policies', to='tunnels.tunnel')),
            ],
        ),
    ]
