# Generated by Django 6.0 on 2026-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsecpolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
