# Generated by Django 6.0.1 on 2026-01-14 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('gateways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ike_sa_id', models.CharField(blank=True, max_length=128, null=True)),
                ('connection_name', models.CharField(max_length=128, unique=True)),
                ('virtual_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DISCONNECTED', 'Disconnected'), ('CONNECTING', 'Connecting'), ('ESTABLISHED', 'Established'), ('REKEYING', 'Rekeying'), ('FAILED', 'Failed')], default='DISCONNECTED', max_length=32)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_rekey', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tunnel', to='devices.device')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnels', to='gateways.vpngateway')),
            ],
        ),
    ]
