# Generated by Django 6.0 on 2026-01-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_subnet', models.CharField(max_length=64)),
                ('remote_subnet', models.CharField(max_length=64)),
                ('peer_ip', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=False)),
                ('last_rekey', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.ipsecpolicy')),
            ],
        ),
    ]
